---
- name: install dependencies for nginx
  yum:
    name: "{{item.name}}"
    state: latest
  loop:
    - name: zlib
    - name: zlib-devel
    - name: gcc
    - name: wget
    - name: openssl
    - name: openssl-devel
    - name: gd
    - name: gd-devel
    - name: libxml2-devel
    - name: libxslt-devel

- name: Include nginx variables.
  include_vars: nginx_vars.yml

- name: Unarchive a file that needs to be downloaded
  unarchive:
    src: http://nginx.org/download/nginx-1.15.1.tar.gz
    dest: /usr/local/src/
    remote_src: yes

- name: Configure nginx
  command: |
    ./configure \
    --prefix=/etc/nginx \
    --http-log-path=/var/log/nginx/access.log \
    --error-log-path=/var/log/nginx/error.log \
    --lock-path=/var/lock/nginx.lock \
    --pid-path=/run/nginx.pid \
    --http-client-body-temp-path=/var/lib/nginx/body \
    --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
    --http-proxy-temp-path=/var/lib/nginx/proxy \
    --http-scgi-temp-path=/var/lib/nginx/scgi \
    --http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
    --with-debug \
    --with-pcre-jit \
    --with-http_dav_module \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_realip_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_image_filter_module \
    --with-http_v2_module \
    --with-http_xslt_module \
    --with-stream \
    --with-stream_ssl_module \
    --with-mail \
    --with-mail_ssl_module \
    --with-threads \
  args:
    chdir: /usr/local/src/nginx-1.15.1

- name: Build nginx
  make:
    chdir: /usr/local/src/nginx-1.15.1

- name: Install nginx
  make:
    chdir: /usr/local/src/nginx-1.15.1
    target: install

- name: Ensure group nginx exists
  group:
    name: nginx
    state: present

- name: Add nginx user and group
  user:
    name: nginx
    group: nginx
    create_home: no

- name: Create nginx directory
  file:
    path: /var/lib/nginx/
    owner: root
    group: root
    mode: 0644
    state: directory

- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Create health.txt for health check.
  template:
    src: "nginx-health.txt.j2"
    dest: "/etc/nginx/html/health.txt"
    owner: root
    group: root
    mode: 0644

- name: Copy nginx server configurations in place.
  template:
    src: "nginx-{{item}}.conf.j2"
    dest: "/etc/nginx/conf/nginx-{{item}}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ nginx_server_confs }}"
  notify:
    - reload nginx

- name: Create nginx.service
  template:
    src: "nginx.service.j2"
    dest: /usr/lib/systemd/system/nginx.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: set auto start nginx
  service:
    name: nginx
    state: started
    enabled: yes
