---
- name: Instal mysql-devel
  yum:
    name: mysql-devel
    state: present

- name: Create puma.service
  template:
    src: "puma.service.j2"
    dest: /usr/lib/systemd/system/puma.service
    owner: root
    group: root
    mode: 0644

- name: Create run directory
  file:
    path: "{{puma_run_path}}"
    owner: root
    group: root
    mode: 0644
    state: directory

- name: Copy logrotate file for rails application.
  become: yes
  template:
    src: rails_logrotate.j2
    dest: /etc/logrotate.d/rails
    owner: root
    group: root
    mode: 0644

- name: set auto start puma
  service:
    name: puma
    enabled: yes

